FROM alcgen:latest

WORKDIR /app
COPY webapp/ webapp/
RUN pip install --no-cache-dir -r webapp/requirements.txt

ENV PYTHONPATH=/app

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "webapp/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
